// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: T4-S3_bluetooth_macropad

#ifndef _T4_S3_BLUETOOTH_MACROPAD_UI_H
#define _T4_S3_BLUETOOTH_MACROPAD_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include <lvgl.h>

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(
    ui_img_fingerprint_45dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/fingerprint_45dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_memory_alt_45dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/memory_alt_45dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_device_thermostat_45dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/device_thermostat_45dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_memory_45dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/memory_45dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_close_45dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/close_45dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_bluetooth_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/bluetooth_90dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_usb_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/usb_90dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_info_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/info_90dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_mimo_disconnect_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/mimo_disconnect_90dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_replay_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/replay_90dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_settings_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/settings_90dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_skip_previous_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/skip_previous_90dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_play_pause_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/play_pause_90dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_skip_next_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/skip_next_90dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_volume_mute_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/volume_mute_90dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_volume_down_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/volume_down_90dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png
LV_IMG_DECLARE(
    ui_img_volume_up_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);    // assets/volume_up_90dp_E3E3E3_FILL0_wght400_GRAD0_opsz48.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
