// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: T4-S3_bluetooth_macropad

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_heater = NULL;
lv_obj_t * ui_heaterContent = NULL;
lv_obj_t * ui_battery = NULL;
lv_obj_t * ui_batteryPourcentage = NULL;
lv_obj_t * ui_batteryIcon = NULL;
lv_obj_t * ui_tab1 = NULL;
lv_obj_t * ui_device1Btn = NULL;
lv_obj_t * ui_Image1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_device2Btn = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_device3Btn = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_disconnectBtn = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_rebootBtn = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_settingBtn = NULL;
lv_obj_t * ui_settingIcon = NULL;
lv_obj_t * ui_Label6 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_heater = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_heater, 600);
    lv_obj_set_height(ui_heater, 50);
    lv_obj_set_x(ui_heater, 0);
    lv_obj_set_y(ui_heater, -200);
    lv_obj_set_align(ui_heater, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_heater, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_heater, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_heater, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_heaterContent = lv_label_create(ui_heater);
    lv_obj_set_width(ui_heaterContent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_heaterContent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_heaterContent, LV_ALIGN_CENTER);

    ui_battery = lv_obj_create(ui_heater);
    lv_obj_set_width(ui_battery, 200);
    lv_obj_set_height(ui_battery, 50);
    lv_obj_set_align(ui_battery, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_battery, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_battery, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_battery, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_batteryPourcentage = lv_label_create(ui_battery);
    lv_obj_set_width(ui_batteryPourcentage, 100);
    lv_obj_set_height(ui_batteryPourcentage, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_batteryPourcentage, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_batteryPourcentage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_batteryPourcentage, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_batteryIcon = lv_bar_create(ui_battery);
    lv_bar_set_value(ui_batteryIcon, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_batteryIcon, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_batteryIcon, 50);
    lv_obj_set_height(ui_batteryIcon, 10);
    lv_obj_set_align(ui_batteryIcon, LV_ALIGN_CENTER);

    ui_tab1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_tab1, 600);
    lv_obj_set_height(ui_tab1, 425);
    lv_obj_set_x(ui_tab1, 0);
    lv_obj_set_y(ui_tab1, 25);
    lv_obj_set_align(ui_tab1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_tab1, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_tab1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_tab1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_device1Btn = lv_btn_create(ui_tab1);
    lv_obj_set_width(ui_device1Btn, 180);
    lv_obj_set_height(ui_device1Btn, 180);
    lv_obj_set_align(ui_device1Btn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_device1Btn, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_device1Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_device1Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_device1Btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_device1Btn);
    lv_img_set_src(ui_Image1, &ui_img_bluetooth_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_device1Btn);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Device 1");

    ui_device2Btn = lv_btn_create(ui_tab1);
    lv_obj_set_width(ui_device2Btn, 180);
    lv_obj_set_height(ui_device2Btn, 180);
    lv_obj_set_align(ui_device2Btn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_device2Btn, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_device2Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_device2Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_device2Btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_device2Btn);
    lv_img_set_src(ui_Image2, &ui_img_bluetooth_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Image2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Image2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_device2Btn);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Device 2");

    ui_device3Btn = lv_btn_create(ui_tab1);
    lv_obj_set_width(ui_device3Btn, 180);
    lv_obj_set_height(ui_device3Btn, 180);
    lv_obj_set_align(ui_device3Btn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_device3Btn, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_device3Btn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_device3Btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_device3Btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image3 = lv_img_create(ui_device3Btn);
    lv_img_set_src(ui_Image3, &ui_img_usb_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_device3Btn);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Device 3");

    ui_disconnectBtn = lv_btn_create(ui_tab1);
    lv_obj_set_width(ui_disconnectBtn, 180);
    lv_obj_set_height(ui_disconnectBtn, 180);
    lv_obj_set_align(ui_disconnectBtn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_disconnectBtn, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_disconnectBtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_disconnectBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_disconnectBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image4 = lv_img_create(ui_disconnectBtn);
    lv_img_set_src(ui_Image4, &ui_img_mimo_disconnect_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_disconnectBtn);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Disconnect");

    ui_rebootBtn = lv_btn_create(ui_tab1);
    lv_obj_set_width(ui_rebootBtn, 180);
    lv_obj_set_height(ui_rebootBtn, 180);
    lv_obj_set_align(ui_rebootBtn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_rebootBtn, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_rebootBtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_rebootBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_rebootBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_rebootBtn);
    lv_img_set_src(ui_Image5, &ui_img_replay_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_rebootBtn);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Reboot");

    ui_settingBtn = lv_btn_create(ui_tab1);
    lv_obj_set_width(ui_settingBtn, 180);
    lv_obj_set_height(ui_settingBtn, 180);
    lv_obj_set_align(ui_settingBtn, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_settingBtn, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_settingBtn, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingBtn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settingBtn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settingIcon = lv_img_create(ui_settingBtn);
    lv_img_set_src(ui_settingIcon, &ui_img_settings_90dp_e3e3e3_fill0_wght400_grad0_opsz48_png);
    lv_obj_set_width(ui_settingIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_settingIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingIcon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_settingIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_settingBtn);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Setting");

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_heater = NULL;
    ui_heaterContent = NULL;
    ui_battery = NULL;
    ui_batteryPourcentage = NULL;
    ui_batteryIcon = NULL;
    ui_tab1 = NULL;
    ui_device1Btn = NULL;
    ui_Image1 = NULL;
    ui_Label1 = NULL;
    ui_device2Btn = NULL;
    ui_Image2 = NULL;
    ui_Label2 = NULL;
    ui_device3Btn = NULL;
    ui_Image3 = NULL;
    ui_Label3 = NULL;
    ui_disconnectBtn = NULL;
    ui_Image4 = NULL;
    ui_Label4 = NULL;
    ui_rebootBtn = NULL;
    ui_Image5 = NULL;
    ui_Label5 = NULL;
    ui_settingBtn = NULL;
    ui_settingIcon = NULL;
    ui_Label6 = NULL;

}
