// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: T4-S3_bluetooth_macropad

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_heater;
extern lv_obj_t * ui_heaterContent;
extern lv_obj_t * ui_infoTab;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_MACTitle;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_chipTitle;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_temperatureTitle;
extern lv_obj_t * ui_Label18;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Image9;
extern lv_obj_t * ui_memoryTitle;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_settingTab;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Image11;
extern lv_obj_t * ui_BrightnessTitle;
extern lv_obj_t * ui_pourcentage;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image15;
extern lv_obj_t * ui_main;
extern lv_obj_t * ui_mainTab;
extern lv_obj_t * ui_tab1;
extern lv_obj_t * ui_device1Btn;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_device2Btn;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_infoBtn;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_disconnectBtn;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_rebootBtn;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_settingBtn;
extern lv_obj_t * ui_settingIcon;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_mediaTab;
extern lv_obj_t * ui_tab2;
extern lv_obj_t * ui_previousBtn;
extern lv_obj_t * ui_previousIcon;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_pausePlayBtn;
extern lv_obj_t * ui_pausePlayIcon;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_nextBtn;
extern lv_obj_t * ui_nextIcon;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_muteBtn;
extern lv_obj_t * ui_muteIcon;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_volumeDownBtn;
extern lv_obj_t * ui_volumeDownIcon;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_volumeUpBtn;
extern lv_obj_t * ui_volumeUpIcon;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_appTab;
extern lv_obj_t * ui_tab3;
extern lv_obj_t * ui_browserBtn;
extern lv_obj_t * ui_browserIcon;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_discordBtn;
extern lv_obj_t * ui_disocrdIcon;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_facebookBtn;
extern lv_obj_t * ui_facebookIcon;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_trerminalBtn;
extern lv_obj_t * ui_terminalIcon;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_vscodeBtn;
extern lv_obj_t * ui_vscodeIcon;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_githubBtn;
extern lv_obj_t * ui_githubIcon;
extern lv_obj_t * ui_Label22;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

